/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-09-14 06:11:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class accountList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1694496219252L));
    _jspx_dependants.put("jar:file:/C:/BNK/work_web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AccoutProject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1694661939470L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>BNK 부산은행 계좌 서비스</title>\r\n");
      out.write("<style>\r\n");
      out.write("nav {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	/*  너비 */\r\n");
      out.write("	height: 80px;\r\n");
      out.write("	/* 높이 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav a:hover {\r\n");
      out.write("	text-decoration: underline;\r\n");
      out.write("	color: #cb2b11;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar ul {\r\n");
      out.write("	padding-left: 0;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo_img {\r\n");
      out.write("	width: 180px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar .left {\r\n");
      out.write("	margin-right: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar li {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar>li>a {\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-size: 17px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	line-height: 50px;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	text-overflow: ellipsis;\r\n");
      out.write("	margin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar>li>a:hover {\r\n");
      out.write("	text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar #userName {\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar #logout {\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar #logout:hover {\r\n");
      out.write("	color: #cb2b11;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#profile {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	font-size: 17px;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	padding: 10px 0px;\r\n");
      out.write("	padding-left: 30px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	line-height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#profileImg {\r\n");
      out.write("	width: 40px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav-divider {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 2px;\r\n");
      out.write("	background-color: #cb2b11;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"main-container\">\r\n");
      out.write("		<nav>\r\n");
      out.write("			<ul id=\"navbar\">\r\n");
      out.write("				<li class=\"left\"><a href=\"index.jsp\"> <img id=\"logo_img\"\r\n");
      out.write("						src=\"img/logo.jpg\" />\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li><a href=\"account.do?action=LIST\">계좌목록</a></li>\r\n");
      out.write("				<li><a href=\"regist.jsp\">계좌등록</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<div id=\"nav-divider\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>계좌 목록</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#container {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	width: 1000px;\r\n");
      out.write("	margin-bottom: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	background: #f9f7f9;\r\n");
      out.write("	padding: 15px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#box {\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px\r\n");
      out.write("		rgba(0, 0, 0, 0.23);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search {\r\n");
      out.write("	width: 50%;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	margin-bottom: 5px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: flex-start;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search-warning {\r\n");
      out.write("	padding-top: 20px;\r\n");
      out.write("	font-size:13px;\r\n");
      out.write("	color: grey;\r\n");
      out.write("	background: #f9f7f9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#select-type {\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-right: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search input {\r\n");
      out.write("	width: 80%;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	padding-left: 20px;\r\n");
      out.write("	border: 0px;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search button {\r\n");
      out.write("	width: 20%;\r\n");
      out.write("	min-width: 50px;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	border: 0px;\r\n");
      out.write("	background: #555;\r\n");
      out.write("	color: white;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	float: right;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("	font-size: 28px;\r\n");
      out.write("	color: #333333;\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: 50px 0px 50px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	border-bottom: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table a {\r\n");
      out.write("	color: #333;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	line-height: 1.4;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	word-break: break-all;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	word-break: break-all;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table a:hover {\r\n");
      out.write("	text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table th {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table th, td {\r\n");
      out.write("	padding: 14px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table td {\r\n");
      out.write("	border-top: 1px solid #e7e7e7;\r\n");
      out.write("	text-align: center\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bottom-container {\r\n");
      out.write("	height: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#regist-btn {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	border: 0px;\r\n");
      out.write("	background: #555;\r\n");
      out.write("	color: white;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	float: right;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>계좌 목록</h1>\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<div id=\"box\">\r\n");
      out.write("			<div id=\"search-warning\">* 잔액으로 검색 시 일정 잔액 이상의 계좌를 조회합니다.</div>\r\n");
      out.write("			<form action=\"account.do?action=SEARCH\" method=\"post\">\r\n");
      out.write("				<div id=\"search\">\r\n");
      out.write("					<select id=\"select-type\" name=\"type\">\r\n");
      out.write("						<option value=\"aseq\">계좌번호</option>\r\n");
      out.write("						<option value=\"cseq\">고객번호</option>\r\n");
      out.write("						<option value=\"pseq\">상품번호</option>\r\n");
      out.write("						<option value=\"balance\">잔액</option>\r\n");
      out.write("					</select> <input placeholder=\"검색어를 입력해주세요.\" name=\"keyword\" />\r\n");
      out.write("					<button>검색</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>계좌 번호</th>\r\n");
      out.write("					<th>고객번호</th>\r\n");
      out.write("					<th>상품번호</th>\r\n");
      out.write("					<th>잔액</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("			<div id=\"bottom-container\">\r\n");
      out.write("				<a id=\"regist-btn\" href=\"regist.jsp\">계좌등록</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /accountList.jsp(167,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("a");
      // /accountList.jsp(167,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/accountList.jsp(167,4) '${accountList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${accountList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<tr>\r\n");
            out.write("						<td><a href=\"account.do?action=VIEW&aseq=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.aseq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.aseq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.cseq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.pseq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.balance}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("원</td>\r\n");
            out.write("					</tr>\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
