/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-09-14 06:11:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1694496219252L));
    _jspx_dependants.put("jar:file:/C:/BNK/work_web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AccoutProject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1694661939470L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>BNK 부산은행 계좌 서비스</title>\r\n");
      out.write("<style>\r\n");
      out.write("nav {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	/*  너비 */\r\n");
      out.write("	height: 80px;\r\n");
      out.write("	/* 높이 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav a:hover {\r\n");
      out.write("	text-decoration: underline;\r\n");
      out.write("	color: #cb2b11;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar ul {\r\n");
      out.write("	padding-left: 0;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo_img {\r\n");
      out.write("	width: 180px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar .left {\r\n");
      out.write("	margin-right: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar li {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar>li>a {\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-size: 17px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	line-height: 50px;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	text-overflow: ellipsis;\r\n");
      out.write("	margin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar>li>a:hover {\r\n");
      out.write("	text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar #userName {\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar #logout {\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar #logout:hover {\r\n");
      out.write("	color: #cb2b11;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#profile {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	font-size: 17px;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	padding: 10px 0px;\r\n");
      out.write("	padding-left: 30px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	line-height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#profileImg {\r\n");
      out.write("	width: 40px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav-divider {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 2px;\r\n");
      out.write("	background-color: #cb2b11;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"main-container\">\r\n");
      out.write("		<nav>\r\n");
      out.write("			<ul id=\"navbar\">\r\n");
      out.write("				<li class=\"left\"><a href=\"index.jsp\"> <img id=\"logo_img\"\r\n");
      out.write("						src=\"img/logo.jpg\" />\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li><a href=\"account.do?action=LIST\">계좌목록</a></li>\r\n");
      out.write("				<li><a href=\"regist.jsp\">계좌등록</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<div id=\"nav-divider\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>계좌등록</title>\r\n");
      out.write("<style>\r\n");
      out.write("#container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	margin-top: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("	width: 500px;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px\r\n");
      out.write("		rgba(0, 0, 0, 0.23);\r\n");
      out.write("	padding: 3%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#back-btn {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	border: none;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#banner {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-item {\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-item label {\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	font-size: medium;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form input {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	border-color: lightgrey;\r\n");
      out.write("	border-style: solid;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form input:focus {\r\n");
      out.write("	border-width: 3px;\r\n");
      out.write("	border-color: #555;\r\n");
      out.write("	outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#cont {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	border-width: 2px;\r\n");
      out.write("	border-color: lightgrey;\r\n");
      out.write("	border-style: solid;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	height: 150px;\r\n");
      out.write("	resize: none;\r\n");
      out.write("	outline-color: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#form-btn-container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-checkbox {\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-checkbox input {\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".div-checkbox {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#conts {\r\n");
      out.write("	width: 20px;\r\n");
      out.write("	height: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-btn {\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	width: 45%;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	font-weight: bolder;\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("	-webkit-transition: .3s ease-in-out;\r\n");
      out.write("	transition: .3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-btn:hover {\r\n");
      out.write("	opacity: .5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-btn[type=submit] {\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: #555;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	function goBack() {\r\n");
      out.write("		window.history.back();\r\n");
      out.write("	}\r\n");
      out.write("	function validatePassword() {\r\n");
      out.write("		if (password.value == password_check.value) {\r\n");
      out.write("			return true;\r\n");
      out.write("		} else {\r\n");
      out.write("			alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("			password_check.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<form action=\"account.do?action=REGIST\" method=\"post\">\r\n");
      out.write("			<button type=\"button\" id=\"back-btn\" onclick=\"javascript:goBack()\">&lt;</button>\r\n");
      out.write("			<h2 id=\"banner\">계좌등록</h2>\r\n");
      out.write("			<div class=\"form-item\">\r\n");
      out.write("				<label for=\"aseq\">계좌번호</label> \r\n");
      out.write("				<input type=\"text\" id=\"aseq\"\r\n");
      out.write("					name=\"aseq\" maxlength=\"20\" required />\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-item\">\r\n");
      out.write("				<label for=\"cseq\">고객번호</label> \r\n");
      out.write("				<input type=\"number\" id=\"cseq\"\r\n");
      out.write("					name=\"cseq\" maxlength=\"10\" required />\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-item\">\r\n");
      out.write("				<label for=\"pseq\">상품번호</label> \r\n");
      out.write("				<input type=\"number\" id=\"pseq\"\r\n");
      out.write("					name=\"pseq\" maxlength=\"10\" required />\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-item\">\r\n");
      out.write("				<label for=\"balance\">잔액</label> \r\n");
      out.write("				<input type=\"number\" id=\"balance\"\r\n");
      out.write("					name=\"balance\" maxlength=\"11\" required />\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-item\">\r\n");
      out.write("				<label for=\"password\">비밀번호</label> \r\n");
      out.write("				<input type=\"password\" id=\"password\"\r\n");
      out.write("				placeholder=\"6자리 숫자를 입력해주세요.\"\r\n");
      out.write("					name=\"password\" minlength=\"6\" maxlength=\"6\" required />\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"form-btn-container\">\r\n");
      out.write("				<input class=\"form-btn\" type=\"reset\" value=\"초기화\" /> <input\r\n");
      out.write("					class=\"form-btn\" type=\"submit\" value=\"계좌등록\" \r\n");
      out.write("					onclick=\"return confirm('정말로 계좌를 등록하시겠습니까?')\"/>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
